### ISSUE TITLE
What's the benefit of this?

### ISSUE THREAD

**Issue by trusktr** [webcomponents/react-integration#39]
We can already use custom elements inside React because they're treated just like native elements, f.e.

```js
class ReactComponent extends React.Component {
  render() {
    return <some-custom-element></some-custom-element>
  }
}
```

Do we need this in order to make it possible to extend the custom element class when creating React components? What other benefits?

**Comment by stevemao** [comment]
But you won't be able to sync events, transfer your properties etc automatically.

**Comment by trusktr** [comment]
@stevemao Oh okay. Maybe I'll realize the importance when I run into it. But maybe it's not a problem if the web component is designed to use only string input on the attributes?

**Comment by stevemao** [comment]
> But maybe it's not a problem if the web component is designed to use only string input on the attributes?

Not sure what you mean. It only transfers the props not attrs.

**Comment by treshugart** [comment]
The benefits are in the bullet points, but to re-iterate:

1. Pass the constructor as the tag name in JSX
2. Sets props - not attributes - so you can pass down any data type to your WCs without having to serialise / deserialise (this is actually something you've proposed in the W3C issues IIRC)
3. Can "react" to synthetic events emitted from a WC

1 is syntactic sugar and nice because you're not hard-coding tag names. 2 is a gripe that many Reacters have with WC and HTML in general. This helps to alleviate that. 3 is actually a limitation of Reacts event system and something they mention [here](https://facebook.github.io/react/docs/webcomponents.html).

> But maybe it's not a problem if the web component is designed to use only string input on the attributes?

This depends on the component, but I don't think it's very practical to assume. There's a nice perf benefit to setting props instead of attributes, too. I can't find the link at the moment but I believe it's about 3 times as fast to set props than attrs.
